Lab_4/lab_4/cart/urls.py
from django.urls import path
from . import views

app_name = "cart"

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/',
         views.cart_add,
         name='cart_add'),
    path('remove/<int:product_id>/',
         views.cart_remove,
         name='cart_remove'),
]

Lab_4/lab_4/lab_4/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static



urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls', namespace='cart')),
    path('order/', include('order.urls', namespace='orders')),
    path('statistic/', include('statistic.urls', namespace='statistic')),
    path('', include('store.urls', namespace='store')),
    path('auth/', include('login.urls', namespace='login'))   
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Lab_4/lab_4/login/urls.py
from . import views
from django.urls import path

app_name = 'login'

urlpatterns = [
    path('register/', views.RegisterFormView.as_view(), name='register'),
    path('account', views.AccountView.as_view() , name='personal_account'),
    path('login/', views.LoginFormView.as_view(), name='login'),
    path('logout/', views.LogoutView.as_view(), name='logout')
]

Lab_4/lab_4/store/urls.py
from django.urls import path
from . import views

app_name = 'store'

urlpatterns = [
     path('', views.product_list, name='product_list'),
     path('about_company/', views.about_company, name='about_company'),
     path('example/', views.example, name='scroll_paralax'),
     path('home_page', views.home_page, name='home_page'),
     path('news', views.news, name = 'news'),
     path('article/<int:id>', views.article_detail, name = 'article-detail'),
     path('questions' , views.frequently_questions , name='frequently_questions'),
     path('contacts', views.workers_info, name="contacts"),
     path('privacy-policy', views.privacy_policy, name ="privacy_policy"),
     path('reviews', views.reviews , name ='reviews'),
     path('review/create', views.create_review, name='create_review'),
     path('vacancies', views.vacancies, name = 'vacancies'),
     path('cupons', views.coupons, name = 'coupons'),
     path('miscellaneous', views.miscellaneous, name = 'miscellaneous'),
     path('<int:id>', views.product_detail,
          name='product_detail'),
     path("create/", views.product_create),
     path("edit/<int:id>/", views.product_edit),
     path("delete/<int:id>/", views.product_delete),
     
     path('<str:product_type_name>/', views.product_list,
          name='product_list_by_category'
          ),
]

Lab_4/lab_4/store/models.py
from django.db import models
from django.urls import reverse
from login.models import CustomUser
# Create your models here.

GRADLE_CHOICES = [(x, x * '★') for x in range (1, 6)]

class ProductType(models.Model) :
    
    name = models.CharField(max_length=200,
                             help_text='Enter product type')

    def get_absolute_url(self):
        return reverse('store:product_list_by_category', args=[str(self.name)])
    
    def __str__(self) :
        return self.name
    
class Producer(models.Model) :

    name = models.CharField(max_length=200,
                            help_text='Enter prodecer name')
    country = models.CharField(max_length=200,
                               help_text='Enter producer country')

    def get_absolute_url(self):
        return reverse('producer-detail', args=[str(self.id)])

    def __str__(self) :
        return self.name 
    
class Product(models.Model) :

    name = models.CharField(max_length=200)
    producer = models.ForeignKey('Producer',
                                    on_delete = models.SET_NULL,
                                    null = True)
    cost = models.IntegerField()
    type = models.ForeignKey('ProductType', 
                                on_delete = models.SET_NULL,
                                null = True)
    quantity = models.IntegerField()
    description = models.TextField()
    image = models.ImageField(upload_to='product/%Y/%m/%d', blank=True)
    purchase_count = models.PositiveIntegerField(default=0)
    UNITS = (
        ('L', 'liter'),
        ('KG', 'kilogramm'),
        ('PC', 'pieces')
    )
    
    units = models.CharField(max_length=2,
                            choices=UNITS,
                            help_text="units of product")

    def get_absolute_url(self):
        return reverse('store:product_detail', args=[str(self.id)])

    def __str__(self) :
        return self.name   
    
class Article(models.Model) :

    title = models.CharField(max_length=200,
                             help_text='Enter article title')
    short_argument = models.CharField(max_length=100)
    content = models.TextField()
    image = models.ImageField(upload_to='article')
    date_of_creation = models.DateTimeField(auto_now_add=True)

    def get_absolute_url(self):
        return reverse('article-detail', args=[str(self.id)])

    def __str__(self) :
        return self.title
    
class Advertisement(models.Model) :

    adv_name = models.CharField(max_length=100)
    image = models.ImageField(upload_to='advertisement')
    link = models.CharField(max_length=200)

    def get_absolute_url(self):
        return reverse('advertisement-detail', args=[str(self.id)])

    def __str__(self) :
        return self.adv_name
    
class Partner(models.Model) :
    partner_name = models.CharField(max_length=100)
    description = models.CharField(max_length=200)
    image = models.ImageField(upload_to='partner')
    link = models.CharField(max_length=200)

    def get_absolute_url(self):
        return reverse('partner-detail', args=[str(self.id)])

    def __str__(self) :
        return self.partner_name
    
class Question(models.Model) :

    question = models.CharField(max_length=100)
    answer = models.TextField()
    date_of_creation = models.DateTimeField(auto_now_add=True)

    def get_absolute_url(self):
        return reverse('question-detail', args=[str(self.id)])

    def __str__(self) :
        return self.question
    
class WorkerInfo(models.Model) :

    worker = models.OneToOneField(CustomUser, on_delete=models.CASCADE, 
                               limit_choices_to={'is_staff': True})
    image = models.ImageField(upload_to="worker_info")
    description = models.TextField()

    def get_absolute_url(self):
        return reverse('worker-info-detail', args=[str(self.id)])

    def __str__(self) :
        return '{0}, {1}'.format(self.worker.first_name, self.worker.last_name)
    
    class Meta:
        verbose_name_plural = 'Workers info'

class Vacancy(models.Model) :

    name = models.CharField(max_length=100)
    salary = models.PositiveIntegerField()
    description = models.TextField()
    date_of_creation = models.DateTimeField(auto_now_add=True)

    def get_absolute_url(self):
        return reverse('vacancy-detail', args=[str(self.id)])

    def __str__(self) :
        return self.name
    
    class Meta:
        verbose_name_plural = 'Vacancies'

class Review(models.Model) :

    title = models.CharField(max_length=200)
    gradle = models.PositiveIntegerField(choices=GRADLE_CHOICES)
    text = models.TextField(max_length=1000)
    date_of_creation = models.DateTimeField(auto_now_add=True)
    owner = models.ForeignKey(CustomUser, on_delete=models.CASCADE)

    def get_absolute_url(self):
        return reverse('review-detail', args=[str(self.id)])

    def __str__(self) :
        return self.title

class Coupon(models.Model) :

    discount = models.PositiveIntegerField()
    date_of_creation = models.DateTimeField(auto_now_add=True)
    code = models.CharField(max_length=50)
    active = models.BooleanField()

    def get_absolute_url(self):
        return reverse('coupon-detail', args=[str(self.id)])

    def __str__(self) :
        return '{0}, {1}'.format(self.date_of_creation, self.discount)
    
class History(models.Model) :

    year = models.IntegerField()
    event = models.CharField(max_length=100)

    def get_absolute_url(self):
        return reverse('history-detail', args=[str(self.id)])

    def __str__(self) :
        return '{0}, {1}'.format(self.year, self.event)
    
    class Meta:
        verbose_name_plural = 'History'

class RotationTime(models.Model):
    time = models.IntegerField()

Lab_4/lab_4/store/forms.py
from django import forms
from .models import Product, Review, GRADLE_CHOICES


class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = ['name', 'producer', 'cost', 'type', 'description', 'image', 'units']

class ReviewForm(forms.ModelForm):
    class Meta:
        model = Review
        fields = ['title', 'text', 'gradle']
        widgets = {'gradle' : forms.Select(choices=GRADLE_CHOICES) }

Lab_4/lab_4/store/views.py
from django.shortcuts import render, get_object_or_404
from .models import *
from cart.forms import CartAddProductForm
from django.http import HttpResponseRedirect
from django.http import HttpResponseNotFound
from .forms import ProductForm, ReviewForm
from django.core.exceptions import PermissionDenied
import requests
import random
from docx import Document

def product_list(request, product_type_name = None):
    product_type = None
    types = ProductType.objects.all()
    products = Product.objects.all();

    if product_type_name:
        product_type = get_object_or_404(ProductType, name = product_type_name)
        products = products.filter(type = product_type)

    sort = request.GET.get('sort')
    if sort == 'ascending':
        products = products.order_by('cost')
    elif sort == 'descending':
        products = products.order_by('-cost')

    return render(request, 'store/product/list.html',
                  {
                      'type': product_type,
                      'types': types,
                      'products': products,
                  })


def product_detail(request, id):
    product = get_object_or_404(Product, id=id)
    cart_product_form = CartAddProductForm()
    joke = requests.get('https://official-joke-api.appspot.com/jokes/programming/random').json()[0]

    return render(request, 'store/product/detail.html', {'product': product,
                                                   'cart_product_form': cart_product_form,
                                                   'joke': joke['setup'] + joke['punchline']})


 
# сохранение данных в бд
def product_create(request):
    if not request.user.is_staff:
        raise PermissionDenied("You do not have access to this page.")

    form = ProductForm()

    if request.method == "POST":
        
        product = Product.objects.create(name=request.POST.get('name'),
                                         producer=Producer.objects.get(id=request.POST.get('producer')),
                                         cost=request.POST.get('cost'),
                                         type=ProductType.objects.get(id=request.POST.get('type')),
                                         quantity=0,
                                         description=request.POST.get('description'),
                                         image=request.FILES.get('image'),
                                         units=request.POST.get('units'))

        product.save()
        return HttpResponseRedirect("/")
    else:
        return render(request, "store/product/create.html", {"form" : form})
    
 
# изменение данных в бд
def product_edit(request, id):
    if not request.user.is_staff:
        raise PermissionDenied("You do not have access to this page.")

    try:
        product = Product.objects.get(id=id)
        form = ProductForm(initial={'name':product.name, 'producer':product.producer,
                                    'cost':product.cost, 'type':product.type, 
                                    'description':product.description, 'image':product.image,
                                    'units':product.units})

        if request.method == "POST":
            product.producer=Producer.objects.get(id=request.POST.get('producer'))
            product.cost=request.POST.get('cost')
            product.type=ProductType.objects.get(id=request.POST.get('type'))
            product.description=request.POST.get('description')
            if request.FILES.get('image') != None:
                product.image=request.FILES.get('image')
            product.units=request.POST.get('units')

            product.save()
            return HttpResponseRedirect("/")
        else:
            return render(request, "store/product/edit.html", {"product": product, "form" : form})
    except product.DoesNotExist:
        return HttpResponseNotFound("<h2>product not found</h2>")
     
# удаление данных из бд
def product_delete(request, id):
    if not request.user.is_staff:
        raise PermissionDenied("You do not have access to this page.")

    try:
        product = Product.objects.get(id=id)
        product.delete()
        return HttpResponseRedirect("/")
    except product.DoesNotExist:
        return HttpResponseNotFound("<h2>product not found</h2>")


def about_company(request) :
    history = History.objects.order_by("year")
    return render(request, "store/store/about_company.html", {"history" : history})

def home_page(request) : 
    if (request.method == "POST"):
        try:
            tmp = RotationTime.objects.get(id=1)
        except RotationTime.DoesNotExist:
            tmp = RotationTime.objects.create(id=1)

        tmp.time = request.POST.get('time')
        tmp.save()

    try:
        tmp = RotationTime.objects.get(id=1)
    except RotationTime.DoesNotExist:
        tmp = RotationTime.objects.create(id=1, time=10)


    partners = Partner.objects.all();
    advertisement = Advertisement.objects.all()
    if len(advertisement) > 3 :
        advertisement = random.sample(Advertisement.objects.all(), 3)

    latest_article = Article.objects.order_by("-date_of_creation").first()

    return render(request, "store/store/home_page.html", {"partners" : partners, "advertisement" : advertisement, 
                                                          "latest_article" : latest_article, 
                                                          "time": tmp.time})

def news(request) :
    articles = Article.objects.all()

    return render(request, "store/store/news.html", {"articles" : articles})

def article_detail(request, id) :
    article = get_object_or_404(Article, id = id)

    return render(request, "store/store/article.html", {"article" : article})

def frequently_questions(request) :
    questions = Question.objects.all()

    return render(request, "store/store/frequently_questions.html", {"questions" : questions})

def workers_info(request) :
    workers_info = WorkerInfo.objects.all()

    return render(request, "store/store/contacts.html", {"workers" : workers_info})

def privacy_policy(request) :
    doc = Document("./media/privacy_policy/privacy_policy.docx")
    html = ""

    for paragraph in doc.paragraphs :
        html += "<p>{0}</p>".format(paragraph.text.replace('\n', '<br>'))

    return render(request, "store/store/privacy_policy.html", {"privacy" : html})

def vacancies(request) :
    vacancies = Vacancy.objects.all()

    return render(request, "store/store/vacancies.html", {"vacancies" : vacancies})

def reviews(request) :
    reviews = Review.objects.all()

    return render(request, "store/store/reviews.html", {"reviews" : reviews})

def create_review(request) :
    form = ReviewForm()
    if request.method == 'POST':
        Review.objects.create(title=request.POST.get('title'), gradle = request.POST.get('gradle'),
                                text = request.POST.get('text'), owner = request.user).save()

        return HttpResponseRedirect('/auth/account')
    elif request.method == 'GET' :
        return render(request, 'store/store/create_review.html', {'form': form})
    
def coupons(request) :
    if not request.user.is_staff:
        raise PermissionDenied("You do not have access to this page.")
    
    active_coupons = Coupon.objects.filter(active = True)
    deactive_coupons = Coupon.objects.filter(active = False)

    return render(request, "store/store/coupons.html", {"active_coupons" : active_coupons, "deactive_coupons" : deactive_coupons})

def miscellaneous(request) :
    return render(request, "store/store/miscellaneous.html")

def example(request) :
    return render(request, "store/store/scroll_paralax.html")

Lab_4/lab_4/store/templates/store/store/about_company.html
{% extends "store/base.html" %}
{% load static %}

{% block title %}About copmany{% endblock %}

{% block head %}
    <meta name="description" content="Информация про компанию">
    <meta name="author" content = "Egor Savonchik">
    <link href="{% static "css/about_company.css" %}" rel="stylesheet">
{% endblock %}

{% block header %}
   <section id="top" style="height: 600px;">
        <img src="https://aryan-tayal.github.io/Mountains-Parallax/bg.jpg" id="bg" />
        <h2 id="text">Mountains</h2>
        <img src="https://aryan-tayal.github.io/Mountains-Parallax/man.png" id="man" />
        <img src="https://aryan-tayal.github.io/Mountains-Parallax/clouds_1.png" id="clouds_1" />
        <img src="https://aryan-tayal.github.io/Mountains-Parallax/clouds_2.png" id="clouds_2" />
        <img src="https://aryan-tayal.github.io/Mountains-Parallax/mountain_left.png" id="mountain_left" />
        <img src="https://aryan-tayal.github.io/Mountains-Parallax/mountain_right.png" id="mountain_right" />
      </section>
{% endblock %}
{% block content %}
<main class="sec">
    <h1>About company</h1>
    <p><dfn translate="no" class="company-name"> Savonchik chemistry</dfn> - a young company specializing in the sale of household chemicals</p>
    <h2>Company videos</h2>
    <iframe class="video" width="560" height="315" src="https://www.youtube.com/embed/C32v0SOziEg?si=BK4QeFgPg0Y6UZBW?autoplay=0&controls=0&showinfo=0&rel=0" 
        title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; 
        gyroscope; picture-in-picture; web-share" allowfullscreen>
    </iframe>
    <h2>History by year</h2>
    <ul class="history">
    {% for event in history %}
        <li class="history-item">
            <p class="history-year">{{ event.year }}</p>
            <p class="history-description">{{ event.event }}</p>
        </li>
    {% endfor %}
    </ul>

    <h2>Requisites</h2>
    <section>
        <p class="requisite">МТС: +375 (33)3-022-482</p>
        <p class="requisite">email: egorsavonchik1@gmail.com</p>
    </section>
    <h2>Logo</h2>
    <img class="logotip" src="{% static "img/logotip.jpg" %}" title = "Логотип компании" height="200" width="200">
    <h2>Certificate</h2>
    <section class="sertificate">
        <h3>Сертификат</h3>
        <p>ООО «Приносим радость»</p>
        <p>Юридический адрес: 220073, Республика Беларусь, г. Минск, ул. Смолячкого, д. 40, кв. 26, каб. 2</p>
        <p>УНП 193067319</p>
        <p>Адрес для почтовых отправлений: 220117, а/я 162.</p>
        <p>Свидетельство о государственной регистрации №193067319 от 19 апреля 2018 г. выдано Минским горисполкомом</p>
        <p>Зарегистрировано Министерством информации Республики Беларусь 11 мая 2018 г. в Государственном реестре изготовителей и распространителей бытовой химии изданий Республики Беларусь в качестве распространителя бытовой химии за №3/1656</p>
        <p>Зарегистрирован в Торговом реестре Республики Беларусь 31 мая 2018 г. за №416870</p>
    </section>
    <script src="{% static "js/scroll.js" %}"></script>
</main>
{% endblock %}

Lab_4/lab_4/store/templates/store/store/article.html
{% extends "store/base.html" %}
{% load static %}

{% block title %}Article{% endblock %}

{% block head %}
    <meta name="description" content="Информация о конкретной статье">
    <meta name="author" content = "Egor Savonchik">
    <link href="{% static "css/article.css" %}" rel="stylesheet">
{% endblock %}

{% block content %}
<article class="article-container">
    <section class="article-info">
        <h2>{{ article.title }}</h2> 
        <img src="{{ article.image.url }}">
        <p>{{ article.date_of_creation }}</p>
    </section>
    <p class="article-content">{{ article.content }}</p>
</article>
<footer>
    <a href="{% url "store:news" %}">Back</a>
</footer>
{% endblock %}

Lab_4/lab_4/store/templates/store/store/contacts.html
{% extends "store/base.html" %}
{% load static %}

{% block title %}Contacts{% endblock %}

{% block head %}
    <meta name="description" content="Список контактов работников">
    <meta name="author" content = "Egor Savonchik">
    <link href="{% static "css/contacts.css" %}" rel="stylesheet">
{% endblock %}

{% block content %}
<main>
    <h2>Workers info</h2>
    <section class="workers-list">
    {% for worker in workers %}
        <section class="worker">
            <img class="worker-img" src = "{{ worker.image.url }}" width="200" height="200" title="Фото сотрудника">
            <p>{{ worker.worker.first_name }} {{ worker.worker.last_name }}</p>
            <p>{{ worker.description }}</p>
            <p>Mail: {{ worker.worker.email }}</p>
            <p>Phone number: {{ worker.worker.phone_number }}</p>
        </section>
    {% endfor %}
    </section>
</main>
{% endblock %}

Lab_4/lab_4/store/templates/store/store/coupons.html
{% extends "store/base.html" %}
{% load static %}

{% block title %}Coupons{% endblock %}

{% block head %}
    <meta name="description" content="Список активных и архивированных купонов">
    <meta name="author" content = "Egor Savonchik">
    <link href="{% static "css/coupons.css" %}" rel="stylesheet">
{% endblock %}

{% block content %}
<main>
    <h2>Coupons</h2>
    <h3>Active</h3>
    <ul class="active-list">
        {% for coupon in active_coupons %}
        <li class="active-coupons"><p>{{coupon.name}}</p>
            <ul>
            <li><p>{{coupon.code}}</p></li>
            <li><p><div class="discount">{{coupon.discount}}%</div></p></li>
            <li><div class="container">
                <div class="colorFill"></div>
            </div></li>    
            <li><p>Date of creation: {{ coupon.date_of_creation }}</p></li>
        </ul>
        </li>
        {% endfor %}
    </ul>
    <hr><h3>Archived</h3>
    <ul class="deactive-list">
        {% for coupon in deactive_coupons %}
        <li class="active-coupons"><p>{{coupon.name}}</p>
            <ul>
            <li><p>{{coupon.code}}</p></li>
            <li><p><div class="discount">{{coupon.discount}}%</div></p></li>
            <li><div class="container">
                <div class="colorFill"></div>
            </div></li>    
            <li><p>Date of creation: {{ coupon.date_of_creation }}</p></li>
        </ul>
        </li>
        {% endfor %}
    </ul>
</main>
<script src="{% static "js/coupons.js" %}"></script>
{% endblock %}

Lab_4/lab_4/store/templates/store/store/create_review.html
{% extends "store/base.html" %}
{% load static %}

{% block title %}Create review{% endblock %}

{% block head %}
    <meta name="description" content="Создание отзыва">
    <meta name="author" content = "Egor Savonchik">
    <link href="{% static "css/create_review.css" %}" rel="stylesheet">
{% endblock %}

{% block content %}
<main>
    <form method="post" action="" class="form-container">
        {% csrf_token %}
        <label for="id_title">Title:</label>
        <input type="text" id="id_title" name="title" class="my-class" required><br>
      
        <label for="id_text">Text:</label>
        <textarea id="id_text" name="text" class="my-class" required></textarea><br>
      
        <label for="id_gradle">Gradle:</label>
        <select id="id_gradle" name="gradle" class="my-class" required>
            {% for choice in form.gradle.field.choices %}
                <option value="{{ choice.0 }}">{{ choice.1 }}</option>
            {% endfor %}
        </select><br>
      
        <input type="submit" value="Create review">
      </form>
</main>
{% endblock %}

Lab_4/lab_4/store/templates/store/store/frequently_questions.html
{% extends "store/base.html" %}
{% load static %}

{% block title %}FAQ{% endblock %}

{% block head %}
    <meta name="description" content="Список часто задаваемых вопросов с ответами">
    <meta name="author" content = "Egor Savonchik">
    <link href="{% static "css/frequently_questions.css" %}" rel="stylesheet">
{% endblock %}

{% block content %}
<main> 
    <h2>Popular question</h2>
    {% for question in questions %}
        <details>
            <summary>
                <p class="title">{{ question.question }}</p>
                <p class="date">{{ question.date_of_creation }}</p>
            </summary>
            <p>{{ question.answer }}</p>
        </details>
        <p></p>
    {% endfor %}
</main>
{% endblock %}

Lab_4/lab_4/store/templates/store/store/home_page.html
{% extends "store/base.html" %}
{% load static %}

{% block title %}Home page{% endblock %}

{% block head %}
    <meta name="description" content="главная страница магазина">
    <meta name="author" content = "Egor Savonchik">
    <link href="{% static "css/home_page.css" %}" rel="stylesheet">
    <link href="{% static "css/news.css" %}" rel="stylesheet">
{% endblock %}



{% block content %}
<section style="background: none;">
    <div class="container">
      <h2 class="main-title">Explore.</h2>
      <img src="https://i.ibb.co/rsp6RFJ/bg1.png" class="background" alt="" />
      <img src="https://i.ibb.co/237VsHs/girl1.png" class="girl" alt="" />
      <img src="https://i.ibb.co/BKtjhV2/rock1.png" class="rock" alt="" />
    </div>
    <div class="content">
      <div class="content-images">
        <div>
          <img src="https://i.ibb.co/w4N157P/haridwar.jpg" alt="" />
          <h4>Haridwar</h4>
          <h3>India</h3>
        </div>
        <div>
          <img src="https://i.ibb.co/v4yCXYS/rishikesh.jpg" alt="" />
          <h4>Rishikesh</h4>
          <h3>India</h3>
        </div>
      </div>
      <div>
        <main>
            <h2>Last news</h2>
            <article class="position-object">
                <p>{{ latest_article.title }}</p>
                <p>{{ latest_article.short_argument }}</p>
                <img src="{{ latest_article.image.url }}" width="250" height="250"><br>
                <a href="article/{{ latest_article.id }}"><small>read more</small></a>
            </article>
            <h2>About partners</h2>
            {% for partner in partners %}
                <div class="partner-container">
                    <a href="{{ partner.link }}">{{ partner.partner_name }}</a>
                    <p>{{ partner.description }}</p>
                    <img src="{{ partner.image.url }}" width="200" height="200">
                </div>
            {% endfor %}
            <h2>Advertisement block</h2>
        </main>
        <aside>
        {% for adv in advertisement %}
            <div class="banner">
                <a href="{{ adv.link }} ">
                    <img class="animated-object" src = "{{ adv.image.url }}" width="200" height="200">
                </a>
            </div>
        {% endfor %}
        </aside>
        <script>
            window.time = '{{time}}';
        </script>
        {%if user.is_superuser%}
        <form method="POST">
            {% csrf_token %}
            <label for="interval">Интервал (в секундах):</label>
            <input type="number" id="interval" value="5" name="time">
            <input type="submit">
        </form>
        {% endif %}
        <script src="{% static 'js/banner.js' %}"></script>
      </div>
    </div>
</section>
  <script
    src="https://cdnjs.cloudflare.com/ajax/libs/gsap/3.6.1/gsap.min.js"
    integrity="sha512-cdV6j5t5o24hkSciVrb8Ki6FveC2SgwGfLE31+ZQRHAeSRxYhAQskLkq3dLm8ZcWe1N3vBOEYmmbhzf7NTtFFQ=="
    crossorigin="anonymous"
  ></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/ScrollMagic/2.0.6/ScrollMagic.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/ScrollMagic/2.0.6/plugins/animation.gsap.js"></script>
  <script src="{% static "js/home_scroll.js" %}"></script>
{% endblock %}

Lab_4/lab_4/store/templates/store/store/news.html
{% extends "store/base.html" %}
{% load static %}

{% block title %}News{% endblock %}

{% block head %}
    <meta name="description" content="Последние новости сайта">
    <meta name="author" content = "Egor Savonchik">
    <link href="{% static "css/news.css" %}" rel="stylesheet">
{% endblock %}

{% block content %}
<h2>News</h2>
<section class="news-list">
    {% for article in articles %}
    <article>
        <p><b>{{ article.title }}</b></p>
        <img src = "{{ article.image.url }}" height="250" width="250">
        <p class="short-content">{{ article.short_argument }}</p>
        <a href="article/{{ article.id }}"><small>read more</small></a>
    </article>
    {% endfor %}
</section>

{% endblock %}

Lab_4/lab_4/store/templates/store/store/reviews.html
{% extends "store/base.html" %}
{% load static %}

{% block title %}Reviews{% endblock %}

{% block head %}
    <meta name="description" content="Отзывы на сайт">
    <meta name="author" content = "Egor Savonchik">
    <link href="{% static "css/reviews.css" %}" rel="stylesheet">
{% endblock %}

{% block content %}
<main>
    {% for review in reviews %}
        <section class="review">
            <h3>{{ review.title }}</h3>
            <p>{{ review.text }}</p>
            <p>
                {% for i in "x"|rjust:review.gradle %}
                    ★
                {% endfor %}
            </p>
            <p>{{ review.owner.first_name }}</p>
            <p>{{ review.date_of_creation }}</p>
        </section>
    {% endfor %}
    
    {% if user.is_authenticated %}
        <a class="ref-button" href="{% url 'login:personal_account' %}">Create review</a>
    {% else %}
        <a class="ref-button" href="{% url 'login:register' %}">Create review</a>
    {% endif %}
</main>
{% endblock %}

Lab_4/lab_4/store/templates/store/store/vacancies.html
{% extends "store/base.html" %}
{% load static %}

{% block title %}Vacancies{% endblock %}

{% block head %}
    <meta name="description" content="Список доступных вакансий">
    <meta name="author" content = "Egor Savonchik">
    <link href="{% static "css/vacancies.css" %}" rel="stylesheet">
{% endblock %}

{% block content %}
<h2>Vacancy</h2>
{% for vacancy in vacancies %}
    <section class="vacancy">
        <h3 class="vacancy-name">{{ vacancy.name }}</h3>
        <p class="vacancy-description">{{ vacancy.description }}</p>
        <p class="vacancy-salary">Salary up to {{ vacancy.salary }}</p>
        <p>{{ vacancy.date_of_creation }}</p>
    </section>
{% endfor %}
{% endblock %}