Lab_4/lab_4/cart/urls.py
from django.urls import path
from . import views

app_name = "cart"

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/',
         views.cart_add,
         name='cart_add'),
    path('remove/<int:product_id>/',
         views.cart_remove,
         name='cart_remove'),
]

Lab_4/lab_4/lab_4/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static



urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls', namespace='cart')),
    path('order/', include('order.urls', namespace='orders')),
    path('statistic/', include('statistic.urls', namespace='statistic')),
    path('', include('store.urls', namespace='store')),
    path('auth/', include('login.urls', namespace='login'))   
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Lab_4/lab_4/order/urls.py
from . import views
from django.urls import path

app_name = 'order'

urlpatterns = [
    path('create/', views.order_create, name='order_create'),
    path('coupon', views.coupon_apply, name="coupon_apply")
]

Lab_4/lab_4/store/urls.py
from django.urls import path
from . import views

app_name = 'store'

urlpatterns = [
     path('', views.product_list, name='product_list'),
     path('about_company/', views.about_company, name='about_company'),
     path('example/', views.example, name='scroll_paralax'),
     path('home_page', views.home_page, name='home_page'),
     path('news', views.news, name = 'news'),
     path('article/<int:id>', views.article_detail, name = 'article-detail'),
     path('questions' , views.frequently_questions , name='frequently_questions'),
     path('contacts', views.workers_info, name="contacts"),
     path('privacy-policy', views.privacy_policy, name ="privacy_policy"),
     path('reviews', views.reviews , name ='reviews'),
     path('review/create', views.create_review, name='create_review'),
     path('vacancies', views.vacancies, name = 'vacancies'),
     path('cupons', views.coupons, name = 'coupons'),
     path('miscellaneous', views.miscellaneous, name = 'miscellaneous'),
     path('<int:id>', views.product_detail,
          name='product_detail'),
     path("create/", views.product_create),
     path("edit/<int:id>/", views.product_edit),
     path("delete/<int:id>/", views.product_delete),
     
     path('<str:product_type_name>/', views.product_list,
          name='product_list_by_category'
          ),
]

Lab_4/lab_4/cart/forms.py
from django import forms


PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 21)]


class CartAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(
                                choices=PRODUCT_QUANTITY_CHOICES,
                                coerce=int)
    update = forms.BooleanField(required=False,
                                initial=False,
                                widget=forms.HiddenInput)

Lab_4/lab_4/cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from store.models import Product
from .cart import Cart
from .forms import CartAddProductForm
from django.core.exceptions import PermissionDenied
from order.forms import CouponApplyForm

@require_POST
def cart_add(request, product_id):
    if not request.user.is_authenticated :
        raise PermissionDenied("You do not have access to this page.")

    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product=product,
                 quantity=cd['quantity'],
                 update_quantity=cd['update'])
    return redirect('cart:cart_detail')


def cart_remove(request, product_id):
    if not request.user.is_authenticated :
        raise PermissionDenied("You do not have access to this page.")

    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)
    return redirect('cart:cart_detail')


def cart_detail(request):
    if not request.user.is_authenticated :
        raise PermissionDenied("You do not have access to this page.")

    cart = Cart(request)
    for item in cart:
        item['update_quantity_form'] = CartAddProductForm(initial={'quantity': item['quantity'],
                                                                   'update': True})
    return render(request, 'cart/detail.html', {'cart': cart})

def cart_detail(request):
    cart = Cart(request)
    for item in cart:
        item['update_quantity_form'] = CartAddProductForm(
                            initial={'quantity': item['quantity'],
                            'update': True})
    coupon_apply_form = CouponApplyForm()
    return render(request,
                  'cart/detail.html',
                  {'cart': cart,
                   'coupon_apply_form': coupon_apply_form})

Lab_4/lab_4/cart/templates/cart/detail.html
{% extends "store/base.html" %}
{% load static %}

{% block title %}
  Корзина покупок
{% endblock %}

{% block content %}
  <h1>Корзина покупок</h1>
  <table class="cart">
    <thead>
      <tr>
        <th>Image</th>
        <th>Product</th>
        <th>Update quantity</th>
        <th>Remove</th>
        <th>Quantity</th>
        <th>Unit price</th>
        <th>Cost</th>
      </tr>
    </thead>
    <tbody>
      {% for item in cart %}
        {% with product=item.product %}
          <tr>
            <td>
              <a href="{{ product.get_absolute_url }}">
                <img src="{% if product.image %}{{ product.image.url }}{% else %}{% static 'img/no_image.png' %}{% endif %}">
              </a>
            </td>
            <td>{{ product.name }}</td>
            <td>
              <form action="{% url 'cart:cart_add' product.id %}" method="post">
                {{ item.update_quantity_form.quantity }}
                {{ item.update_quantity_form.update }}
                <input type="submit" value="Обновить">
                {% csrf_token %}
              </form>
            </td>
            <td><a href="{% url 'cart:cart_remove' product.id %}">Удалить</a></td>
            <td>
              {{ item.quantity }}
            </td>
            <td class="num">{{ item.cost }}</td>
            <td class="num">{{ item.total_cost }}</td>
          </tr>
        {% endwith %}
      {% endfor %}
      {% if cart.coupon %}
      <tr class="subtotal">
          <td>Subtotal</td>
          <td colspan="4"></td>
          <td class="num">${{ cart.get_total_price }}</td>
      </tr>
      <tr>
          <td>
              "{{ cart.coupon.code }}" coupon
              ({{ cart.coupon.discount }}% off)
          </td>
          <td colspan="4"></td>
          <td class="num neg">
              - ${{ cart.get_discount|floatformat:"2" }}
          </td>
      </tr>
      {% endif %}
      <tr class="total">
          <td>Total</td>
          <td colspan="4"></td>
          <td class="num">
              ${{ cart.get_total_price_after_discount|floatformat:"2" }}
          </td>
      </tr>
    </tbody>
  </table>
  <form action="{% url "order:coupon_apply" %}" method="post">
    {% csrf_token %}
    <input type="text" name="coupon_code">
    <input type="submit" value="Apply">
  </form>
  <p class="text-right">
    <a href="{% url 'store:product_list' %}" class="button light">В магазин</a>
    <a href="{% url "orders:order_create" %}" class="button">
      Checkout
  </a>
  </p>
{% endblock %}