Lab_4/lab_4/cart/urls.py
from django.urls import path
from . import views

app_name = "cart"

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/',
         views.cart_add,
         name='cart_add'),
    path('remove/<int:product_id>/',
         views.cart_remove,
         name='cart_remove'),
]

Lab_4/lab_4/lab_4/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static



urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls', namespace='cart')),
    path('order/', include('order.urls', namespace='orders')),
    path('statistic/', include('statistic.urls', namespace='statistic')),
    path('', include('store.urls', namespace='store')),
    path('auth/', include('login.urls', namespace='login'))   
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Lab_4/lab_4/login/urls.py
from . import views
from django.urls import path

app_name = 'login'

urlpatterns = [
    path('register/', views.RegisterFormView.as_view(), name='register'),
    path('account', views.AccountView.as_view() , name='personal_account'),
    path('login/', views.LoginFormView.as_view(), name='login'),
    path('logout/', views.LogoutView.as_view(), name='logout')
]

Lab_4/lab_4/store/urls.py
from django.urls import path
from . import views

app_name = 'store'

urlpatterns = [
     path('', views.product_list, name='product_list'),
     path('about_company/', views.about_company, name='about_company'),
     path('example/', views.example, name='scroll_paralax'),
     path('home_page', views.home_page, name='home_page'),
     path('news', views.news, name = 'news'),
     path('article/<int:id>', views.article_detail, name = 'article-detail'),
     path('questions' , views.frequently_questions , name='frequently_questions'),
     path('contacts', views.workers_info, name="contacts"),
     path('privacy-policy', views.privacy_policy, name ="privacy_policy"),
     path('reviews', views.reviews , name ='reviews'),
     path('review/create', views.create_review, name='create_review'),
     path('vacancies', views.vacancies, name = 'vacancies'),
     path('cupons', views.coupons, name = 'coupons'),
     path('miscellaneous', views.miscellaneous, name = 'miscellaneous'),
     path('<int:id>', views.product_detail,
          name='product_detail'),
     path("create/", views.product_create),
     path("edit/<int:id>/", views.product_edit),
     path("delete/<int:id>/", views.product_delete),
     
     path('<str:product_type_name>/', views.product_list,
          name='product_list_by_category'
          ),
]

Lab_4/lab_4/store/models.py
from django.db import models
from django.urls import reverse
from login.models import CustomUser
# Create your models here.

GRADLE_CHOICES = [(x, x * '★') for x in range (1, 6)]

class ProductType(models.Model) :
    
    name = models.CharField(max_length=200,
                             help_text='Enter product type')

    def get_absolute_url(self):
        return reverse('store:product_list_by_category', args=[str(self.name)])
    
    def __str__(self) :
        return self.name
    
class Producer(models.Model) :

    name = models.CharField(max_length=200,
                            help_text='Enter prodecer name')
    country = models.CharField(max_length=200,
                               help_text='Enter producer country')

    def get_absolute_url(self):
        return reverse('producer-detail', args=[str(self.id)])

    def __str__(self) :
        return self.name 
    
class Product(models.Model) :

    name = models.CharField(max_length=200)
    producer = models.ForeignKey('Producer',
                                    on_delete = models.SET_NULL,
                                    null = True)
    cost = models.IntegerField()
    type = models.ForeignKey('ProductType', 
                                on_delete = models.SET_NULL,
                                null = True)
    quantity = models.IntegerField()
    description = models.TextField()
    image = models.ImageField(upload_to='product/%Y/%m/%d', blank=True)
    purchase_count = models.PositiveIntegerField(default=0)
    UNITS = (
        ('L', 'liter'),
        ('KG', 'kilogramm'),
        ('PC', 'pieces')
    )
    
    units = models.CharField(max_length=2,
                            choices=UNITS,
                            help_text="units of product")

    def get_absolute_url(self):
        return reverse('store:product_detail', args=[str(self.id)])

    def __str__(self) :
        return self.name   
    
class Article(models.Model) :

    title = models.CharField(max_length=200,
                             help_text='Enter article title')
    short_argument = models.CharField(max_length=100)
    content = models.TextField()
    image = models.ImageField(upload_to='article')
    date_of_creation = models.DateTimeField(auto_now_add=True)

    def get_absolute_url(self):
        return reverse('article-detail', args=[str(self.id)])

    def __str__(self) :
        return self.title
    
class Advertisement(models.Model) :

    adv_name = models.CharField(max_length=100)
    image = models.ImageField(upload_to='advertisement')
    link = models.CharField(max_length=200)

    def get_absolute_url(self):
        return reverse('advertisement-detail', args=[str(self.id)])

    def __str__(self) :
        return self.adv_name
    
class Partner(models.Model) :
    partner_name = models.CharField(max_length=100)
    description = models.CharField(max_length=200)
    image = models.ImageField(upload_to='partner')
    link = models.CharField(max_length=200)

    def get_absolute_url(self):
        return reverse('partner-detail', args=[str(self.id)])

    def __str__(self) :
        return self.partner_name
    
class Question(models.Model) :

    question = models.CharField(max_length=100)
    answer = models.TextField()
    date_of_creation = models.DateTimeField(auto_now_add=True)

    def get_absolute_url(self):
        return reverse('question-detail', args=[str(self.id)])

    def __str__(self) :
        return self.question
    
class WorkerInfo(models.Model) :

    worker = models.OneToOneField(CustomUser, on_delete=models.CASCADE, 
                               limit_choices_to={'is_staff': True})
    image = models.ImageField(upload_to="worker_info")
    description = models.TextField()

    def get_absolute_url(self):
        return reverse('worker-info-detail', args=[str(self.id)])

    def __str__(self) :
        return '{0}, {1}'.format(self.worker.first_name, self.worker.last_name)
    
    class Meta:
        verbose_name_plural = 'Workers info'

class Vacancy(models.Model) :

    name = models.CharField(max_length=100)
    salary = models.PositiveIntegerField()
    description = models.TextField()
    date_of_creation = models.DateTimeField(auto_now_add=True)

    def get_absolute_url(self):
        return reverse('vacancy-detail', args=[str(self.id)])

    def __str__(self) :
        return self.name
    
    class Meta:
        verbose_name_plural = 'Vacancies'

class Review(models.Model) :

    title = models.CharField(max_length=200)
    gradle = models.PositiveIntegerField(choices=GRADLE_CHOICES)
    text = models.TextField(max_length=1000)
    date_of_creation = models.DateTimeField(auto_now_add=True)
    owner = models.ForeignKey(CustomUser, on_delete=models.CASCADE)

    def get_absolute_url(self):
        return reverse('review-detail', args=[str(self.id)])

    def __str__(self) :
        return self.title

class Coupon(models.Model) :

    discount = models.PositiveIntegerField()
    date_of_creation = models.DateTimeField(auto_now_add=True)
    code = models.CharField(max_length=50)
    active = models.BooleanField()

    def get_absolute_url(self):
        return reverse('coupon-detail', args=[str(self.id)])

    def __str__(self) :
        return '{0}, {1}'.format(self.date_of_creation, self.discount)
    
class History(models.Model) :

    year = models.IntegerField()
    event = models.CharField(max_length=100)

    def get_absolute_url(self):
        return reverse('history-detail', args=[str(self.id)])

    def __str__(self) :
        return '{0}, {1}'.format(self.year, self.event)
    
    class Meta:
        verbose_name_plural = 'History'

class RotationTime(models.Model):
    time = models.IntegerField()

Lab_4/lab_4/store/forms.py
from django import forms
from .models import Product, Review, GRADLE_CHOICES


class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = ['name', 'producer', 'cost', 'type', 'description', 'image', 'units']

class ReviewForm(forms.ModelForm):
    class Meta:
        model = Review
        fields = ['title', 'text', 'gradle']
        widgets = {'gradle' : forms.Select(choices=GRADLE_CHOICES) }

Lab_4/lab_4/store/views.py
from django.shortcuts import render, get_object_or_404
from .models import *
from cart.forms import CartAddProductForm
from django.http import HttpResponseRedirect
from django.http import HttpResponseNotFound
from .forms import ProductForm, ReviewForm
from django.core.exceptions import PermissionDenied
import requests
import random
from docx import Document

def product_list(request, product_type_name = None):
    product_type = None
    types = ProductType.objects.all()
    products = Product.objects.all();

    if product_type_name:
        product_type = get_object_or_404(ProductType, name = product_type_name)
        products = products.filter(type = product_type)

    sort = request.GET.get('sort')
    if sort == 'ascending':
        products = products.order_by('cost')
    elif sort == 'descending':
        products = products.order_by('-cost')

    return render(request, 'store/product/list.html',
                  {
                      'type': product_type,
                      'types': types,
                      'products': products,
                  })


def product_detail(request, id):
    product = get_object_or_404(Product, id=id)
    cart_product_form = CartAddProductForm()
    joke = requests.get('https://official-joke-api.appspot.com/jokes/programming/random').json()[0]

    return render(request, 'store/product/detail.html', {'product': product,
                                                   'cart_product_form': cart_product_form,
                                                   'joke': joke['setup'] + joke['punchline']})


 
# сохранение данных в бд
def product_create(request):
    if not request.user.is_staff:
        raise PermissionDenied("You do not have access to this page.")

    form = ProductForm()

    if request.method == "POST":
        
        product = Product.objects.create(name=request.POST.get('name'),
                                         producer=Producer.objects.get(id=request.POST.get('producer')),
                                         cost=request.POST.get('cost'),
                                         type=ProductType.objects.get(id=request.POST.get('type')),
                                         quantity=0,
                                         description=request.POST.get('description'),
                                         image=request.FILES.get('image'),
                                         units=request.POST.get('units'))

        product.save()
        return HttpResponseRedirect("/")
    else:
        return render(request, "store/product/create.html", {"form" : form})
    
 
# изменение данных в бд
def product_edit(request, id):
    if not request.user.is_staff:
        raise PermissionDenied("You do not have access to this page.")

    try:
        product = Product.objects.get(id=id)
        form = ProductForm(initial={'name':product.name, 'producer':product.producer,
                                    'cost':product.cost, 'type':product.type, 
                                    'description':product.description, 'image':product.image,
                                    'units':product.units})

        if request.method == "POST":
            product.producer=Producer.objects.get(id=request.POST.get('producer'))
            product.cost=request.POST.get('cost')
            product.type=ProductType.objects.get(id=request.POST.get('type'))
            product.description=request.POST.get('description')
            if request.FILES.get('image') != None:
                product.image=request.FILES.get('image')
            product.units=request.POST.get('units')

            product.save()
            return HttpResponseRedirect("/")
        else:
            return render(request, "store/product/edit.html", {"product": product, "form" : form})
    except product.DoesNotExist:
        return HttpResponseNotFound("<h2>product not found</h2>")
     
# удаление данных из бд
def product_delete(request, id):
    if not request.user.is_staff:
        raise PermissionDenied("You do not have access to this page.")

    try:
        product = Product.objects.get(id=id)
        product.delete()
        return HttpResponseRedirect("/")
    except product.DoesNotExist:
        return HttpResponseNotFound("<h2>product not found</h2>")


def about_company(request) :
    history = History.objects.order_by("year")
    return render(request, "store/store/about_company.html", {"history" : history})

def home_page(request) : 
    if (request.method == "POST"):
        try:
            tmp = RotationTime.objects.get(id=1)
        except RotationTime.DoesNotExist:
            tmp = RotationTime.objects.create(id=1)

        tmp.time = request.POST.get('time')
        tmp.save()

    try:
        tmp = RotationTime.objects.get(id=1)
    except RotationTime.DoesNotExist:
        tmp = RotationTime.objects.create(id=1, time=10)


    partners = Partner.objects.all();
    advertisement = Advertisement.objects.all()
    if len(advertisement) > 3 :
        advertisement = random.sample(Advertisement.objects.all(), 3)

    latest_article = Article.objects.order_by("-date_of_creation").first()

    return render(request, "store/store/home_page.html", {"partners" : partners, "advertisement" : advertisement, 
                                                          "latest_article" : latest_article, 
                                                          "time": tmp.time})

def news(request) :
    articles = Article.objects.all()

    return render(request, "store/store/news.html", {"articles" : articles})

def article_detail(request, id) :
    article = get_object_or_404(Article, id = id)

    return render(request, "store/store/article.html", {"article" : article})

def frequently_questions(request) :
    questions = Question.objects.all()

    return render(request, "store/store/frequently_questions.html", {"questions" : questions})

def workers_info(request) :
    workers_info = WorkerInfo.objects.all()

    return render(request, "store/store/contacts.html", {"workers" : workers_info})

def privacy_policy(request) :
    doc = Document("./media/privacy_policy/privacy_policy.docx")
    html = ""

    for paragraph in doc.paragraphs :
        html += "<p>{0}</p>".format(paragraph.text.replace('\n', '<br>'))

    return render(request, "store/store/privacy_policy.html", {"privacy" : html})

def vacancies(request) :
    vacancies = Vacancy.objects.all()

    return render(request, "store/store/vacancies.html", {"vacancies" : vacancies})

def reviews(request) :
    reviews = Review.objects.all()

    return render(request, "store/store/reviews.html", {"reviews" : reviews})

def create_review(request) :
    form = ReviewForm()
    if request.method == 'POST':
        Review.objects.create(title=request.POST.get('title'), gradle = request.POST.get('gradle'),
                                text = request.POST.get('text'), owner = request.user).save()

        return HttpResponseRedirect('/auth/account')
    elif request.method == 'GET' :
        return render(request, 'store/store/create_review.html', {'form': form})
    
def coupons(request) :
    if not request.user.is_staff:
        raise PermissionDenied("You do not have access to this page.")
    
    active_coupons = Coupon.objects.filter(active = True)
    deactive_coupons = Coupon.objects.filter(active = False)

    return render(request, "store/store/coupons.html", {"active_coupons" : active_coupons, "deactive_coupons" : deactive_coupons})

def miscellaneous(request) :
    return render(request, "store/store/miscellaneous.html")

def example(request) :
    return render(request, "store/store/scroll_paralax.html")

Lab_4/lab_4/store/templates/store/base.html
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8" />
        <title>{% block title %}Shop{% endblock %}</title>
        <link href="{% static "css/base.css" %}" rel="stylesheet">
        <link rel="shortcut icon" href="/media/shortcut/site_icon.jpg" />
        {% block head %}{% endblock %}
    </head>
    <body>
        <div id="header" class="nav-bar">
            <nav class="ref-nav">
                <a href="/" class="logo">Shop</a>
                <a class="custom-button" href="{% url "store:home_page" %}">Home</a>
                <a class="custom-button" href="{% url "store:news" %}">News</a>
                <a class="custom-button" href="{% url "store:frequently_questions" %}">FAQ</a>
                <a class="custom-button" href="{% url "store:reviews" %}">Reviews</a>
                {% if user.is_superuser %}
                <a class="custom-button" href="/statistic/">Statistic</a>
                {% endif %}
            </nav> 
        </div>
        <div id="subheader">
                Current Date: <span id='date'></span>
                 | Current time: <span id='time'></span>
                 | Current time zone: <span id='zone'></span>
            <script>
                const today = new Date();
                const yyyy = today.getFullYear();
                let mm = today.getMonth() + 1; // Months start at 0!
                let dd = today.getDate();
                let h = today.getHours();
                if (h<10)
                    h = '0' + h;
                let min = today.getMinutes();
                if (min < 10)
                    min = '0' + min;
                let sec = today.getSeconds();
                if (sec < 10)
                    sec = '0' + sec;

                if (dd < 10) dd = '0' + dd;
                if (mm < 10) mm = '0' + mm;

                let formattedToday = dd + '/' + mm + '/' + yyyy;
                let time = h+":"+min+":"+sec; 
                let tz = -(new Date().getTimezoneOffset() / 60);
                if(tz>0){
                    tz = "+" + tz;
                }
                tz = "UTC" + tz;
                document.getElementById('date').innerHTML=formattedToday;
                document.getElementById('time').innerHTML=time;
                document.getElementById('zone').innerHTML=tz;
            </script>
            <div class="cart">
                {% if user.is_authenticated %}
                {% with total_items=cart|length %}
                {% if cart|length > 0 %}
                In cart:
                <a href="{% url 'cart:cart_detail' %}">
                    {{ total_items }} pcs, {{ cart.get_total_price }} 
                </a>
                {% else %}
                Cart empty
                {% endif %}
                {% endwith %}
                {% endif %}

                {% if user.is_authenticated %}
                | {{ user.username }} |
                <a href="{% url 'login:logout' %}">Out</a>
                {% else %}
                <a href="{% url 'login:login' %}">Sign in</a>
                <a href="{% url 'login:register' %}">Sign up</a>
                {% endif %}
            </div>
        </div>
        {% block header%}
        {% endblock %}
        <main>
            {% block content %}{% endblock %}
        </main>
    </body>
    <tail style="margin-top: 0px;">
        <div class="nav-down">
            <hr style="margin-top: 0px;">
            <nav>
                <a class="custom-button" href="{% url 'store:about_company' %}">About company </a>
                <a class="custom-button" href="{% url 'store:contacts' %}">Contacts </a>
                <a class="custom-button" href="{% url 'store:privacy_policy' %}">Privacy policy</a>
                <a class="custom-button" href="{% url 'store:vacancies' %}">Vacancies</a>
                {% if user.is_staff %}
                    <a class="custom-button" href="{% url 'store:coupons' %}">Coupons</a>
                {% endif %}
                <a class="custom-button" href = "{% url 'store:miscellaneous' %}">Miscellaneous</a>
            </nav>
        </div>
    </tail>
    <script src="{% static "js/custom_ref.js" %}"></script>
</html>